Release 2.0.0
kontent-ai/rich-text-resolver-js pull request #57
Opened 2024-11-04 08:16 UTC by pokornyd

### Motivation

- added resolution capabilities for non-rich-text-native HTML tags
- reworked transformation logic
- updated several naming conventions to better match Kontent.ai counterparts
- improved typing
- fixes #56

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

2025-01-10 07:22 UTC, IvanKiral requested changes

2025-01-10 07:22 UTC, IvanKiral commented on README.md
> +The tool provides environment-aware `parseHtml` function to transform HTML into an array of simplified JSON trees. Any valid HTML is parsed, including all attributes. Together with built-in transform
I would add here (node.js or browser). (not sure if we can use it in Bun or Deno)

2025-01-10 07:22 UTC, IvanKiral commented on README.md
> +The tool provides environment-aware `parseHtml` function to transform HTML into an array of simplified JSON trees. Any valid HTML is parsed, including all attributes. Together with built-in transform
nitpick: `this tool is a...`

2025-01-10 07:22 UTC, IvanKiral commented on README.md
> +Besides default blocks for common elements, Portable Text supports custom blocks, which can represent other entities. Each custom block should extend `ArbitraryTypedObject` to ensure `_key` and `_typ
override meaning transformation?

2025-01-10 07:22 UTC, IvanKiral commented on README.md
> +##### Component/linked item
I would like to have here the names of the types in this h5 title. Something like `##### Component/linked item - PortableTextComponent`

I also like the code snippet so keep it, but with more detailed title it would be easier to find the type. What do you think?

2025-01-10 07:22 UTC, IvanKiral commented on README.md
> +> For image resolution, you may use `resolveImage` helper function. You can provide it either with a custom resolution method or use provided default implementations.
Do we have any example for custom resolution?

2025-01-10 07:22 UTC, IvanKiral commented on README.md
>  ```ts
I am missing import for PortableTextObject in this example :/

2025-01-10 07:22 UTC, IvanKiral commented on docs/index.md
> +To transform the `DomNode` array back to HTML, you can use `nodesToHtml` function or its async variant `nodesToHtmlAsync`. The function accepts the parsed array and a `transformers` object, which def
nitpick: `all remaining tags..`

2025-01-10 07:22 UTC, IvanKiral commented on docs/index.md
> +const transformers: NodeToStringMap = {
I would add import of this type in this example

2025-01-10 07:22 UTC, IvanKiral commented on docs/index.md
> +console.log(htmlOutput); // <p>Hello <strong>World!</strong></p>
This is rather a nitpick, but I would rather see two `consts` then updating the `let` variable.

2025-01-10 07:22 UTC, IvanKiral commented on docs/index.md
> +Example showcasing asynchronous transformation of `<img>` tag to `<figure>`, simultaneously uploading the image to Kontent.ai asset library, using SDK `ManagementClient` provided as context:
this text coincide with the paragraph before to me. Can we graphically distinguish it somehow? Maybe bold or italic text? Or add it as a comment to the code snippet?

2025-01-10 07:22 UTC, IvanKiral commented on docs/index.md
> +type ListContext = {
I would add there comment something like "List context to deal with nested levels of lists"

2025-01-10 07:22 UTC, IvanKiral commented on src/parser/parser-models.ts
> +  "data-external-id": never;
If you had there propety like type: "delivery" and type: "management" in the other one you could discriminate those types on this property and no need for thisd `never` and `undefined` types. Would that be possible? If so, I found it as a more readable solution, if it doesn't break anything.

What do you think?

2025-01-10 07:22 UTC, IvanKiral commented on src/transformers/json-transformer/json-transformer.ts
> +        const transformer = transformers.tag[tagNode.tagName] ?? transformers.tag["*"];
maybe make `transformers.tag["*"]` mandatory?
The type could look something like this
```ts
type RecordWithMandatoryProperty = Record<string, number> & {"*" : number}
```

what do you think?

2025-01-10 07:22 UTC, IvanKiral commented on src/transformers/json-transformer/json-transformer.ts
> +export type NodeToString<TContext = unknown> = (
NodeToHtml or NodeToHtmlString wouldn't be better?

2025-01-10 07:22 UTC, IvanKiral commented on src/transformers/json-transformer/json-transformer.ts
> +              await transformer?.(tagNode, children, updatedContext)
hmm, there is no default implementation for "*" (in case a custom transformer for tag does not exists) in `transformNode` and we throw error, but there is a default implementation for '*'  in `nodesToHtml`. Wouldn't it be better to have default implementation for '*'  (if possible. I guess for `transformNodes`, you could just return some original value?) for both or make transformerFunction for wildcard mandatory? 

I am more inclined to have default implementation for wildcard in both trasnformNodes(Async) and nodesToHtml(Async). What do you think?

2025-01-10 07:22 UTC, IvanKiral commented on src/transformers/json-transformer/json-transformer.ts
> +  exclude: ReadonlyArray<string> = [],
I don't you use this exclude somewhere, so it can be removed?

2025-01-10 07:22 UTC, IvanKiral commented on src/transformers/portable-text-transformer/portable-text-transformer.ts
>  } from "../../transformers/index.js";
this path si kind of overengineered  :D or is this a design choice? :D

2025-01-10 07:22 UTC, IvanKiral commented on src/transformers/portable-text-transformer/portable-text-transformer.ts
> +      const categoryMap: Record<PortableTextItem["_type"], PortableTextItem[]> = {
I am not sure about this :D hopefully, there is some optimalization and not the same object is created every single time

switch, or creating this object before the reduce would be safer

2025-01-10 07:22 UTC, IvanKiral commented on src/transformers/portable-text-transformer/portable-text-transformer.ts
> +const getReferenceData = (attributes: Record<string, string | undefined>): ReferenceData | undefined => {
I would probably split this function into getAssetReferenceData and getItemReferenceData

2025-01-10 07:22 UTC, IvanKiral commented on src/transformers/transformer-models.ts
> +  referenceType?: "codename" | "external-id" | "id";
why is this optional?

2025-01-10 07:22 UTC, IvanKiral commented on src/utils/common-utils.ts
> +export const isTableCell = (node: DomHtmlNode): boolean => isElement(node) && node.tagName === "td";
you get node:DomHtmlNode to function and you check in `isElement` whether node is DomHtmlNode, seems kind of redundant :)

2025-01-10 07:22 UTC, IvanKiral commented on src/utils/transformer-utils.ts
> +export type ResolverFunction<T extends ArbitraryTypedObject> = (
this can be one lined

2025-01-10 07:22 UTC, IvanKiral commented on src/utils/transformer-utils.ts
> +  callback: (node: T) => ArbitraryTypedObject | undefined,
undefined vs null https://kontent-ai.atlassian.net/wiki/spaces/KCD/pages/530439/JavaScript+frontend+conventions#Null-vs-undefined

2025-01-10 07:22 UTC, IvanKiral commented on src/utils/transformer-utils.ts
> +    const traversedNode = callback(node) ?? { ...node };
keep in mind, this is NOT a deep copy... if a node contains an array traversnedNode will reference the same array as node. Is that okay?

2025-01-10 07:22 UTC, IvanKiral commented on src/utils/transformer-utils.ts
>  export const createMark = (
Risa had a Utility type for this 
![image](https://github.com/user-attachments/assets/f797f551-7a11-47d7-b782-f69b1ddace93)

the difference is that intellisense will be whispering you the union type, but you can still use all string :)

2025-01-10 07:22 UTC, IvanKiral commented on tests/transfomers/json-transformer/json-transformer.spec.ts
> +  test("should throw if no tag transformer is specified", () => {
can't we use default 'wildcard' tag in this scenario?

2025-01-10 07:22 UTC, IvanKiral commented on docs/index.md
> +For more complex scenarios, optional context and its handler can be passed to the transformation function as third and fourth parameters respectively. Context can be accessed when defining node trans
can we specify what exactly is tranformation function? are those `transformNodes` and `nodesToHtml`

2025-01-10 07:22 UTC, IvanKiral commented on tests/transfomers/portable-text-transformer/mapi-transformer.spec.ts
> +    expect(secondParsePortableText[0].markDefs[0]).toEqual(secondParsePortableText[0].markDefs[1]); // TODO: fix types
forgotten todo here?

2025-01-10 07:22 UTC, IvanKiral commented on README.md
> +This package provides utilities for transforming Kontent.ai rich text into structured formats suitable for resolution and rendering in various environments.
I am missing some high level overview diagram.
Does something like this make sense?
<img width="1134" alt="image" src="https://github.com/user-attachments/assets/51da3bfa-bf5d-4545-abd8-14a208d40fb8" />

2025-01-13 09:30 UTC, pokornyd commented on README.md
> +This package provides utilities for transforming Kontent.ai rich text into structured formats suitable for resolution and rendering in various environments.
I would swap `Mapi` for `HTML` in the external libraries section. Also, `nodesToPortableText` should point to `Array<PortableTextObject>`. `transformNodes` (`transformNodesAsync`) is the one resulting in custom output. fair point adding a visual overview to clarify the logic

2025-01-13 12:20 UTC, pokornyd commented on tests/transfomers/json-transformer/json-transformer.spec.ts
> +  test("should throw if no tag transformer is specified", () => {
with `nodesToHtml`, we know the desired output is HTML string and we can tailor the fallback behavior accordingly (no wildcard? no problem, here's HTML). 

`transformNodes` on the other hand is generic and returns generic `TOutput[]`, so the only fallback behavior I can think of is returning an empty array. I prefer throwing in that case. If user wants to delete some nodes, they can return an empty array explicitly.

2025-01-13 13:52 UTC, pokornyd commented on src/transformers/transformer-models.ts
> +  referenceType?: "codename" | "external-id" | "id";
shouldn't be. fixed

2025-01-13 15:34 UTC, pokornyd commented on src/transformers/portable-text-transformer/portable-text-transformer.ts
> +const getReferenceData = (attributes: Record<string, string | undefined>): ReferenceData | undefined => {
good point. I actually added three methods: `getAssetReferenceData, getItemOrComponentReferenceData, getItemLinkReferenceData`

2025-01-13 15:44 UTC, pokornyd commented on src/transformers/json-transformer/json-transformer.ts
> +  exclude: ReadonlyArray<string> = [],
I may have toyed with using it elsewhere (MAPI resolution), but let me review it and perhaps remove

2025-01-13 15:51 UTC, pokornyd commented on README.md
> +Besides default blocks for common elements, Portable Text supports custom blocks, which can represent other entities. Each custom block should extend `ArbitraryTypedObject` to ensure `_key` and `_typ
I reworded it completely:
>Value of `_type` property is used for mapping purposes in subsequent resolution.

fine by you?

2025-01-13 16:10 UTC, pokornyd commented on README.md
> +##### Component/linked item
Adjusted titles and tips to provide more detailed info

2025-01-13 16:13 UTC, pokornyd commented on README.md
>  ```ts
yeah, it missed more than that. fixed

2025-01-13 16:13 UTC, pokornyd commented on docs/index.md
> +To transform the `DomNode` array back to HTML, you can use `nodesToHtml` function or its async variant `nodesToHtmlAsync`. The function accepts the parsed array and a `transformers` object, which def
guess it's simpler

2025-01-13 16:15 UTC, pokornyd commented on docs/index.md
> +const transformers: NodeToStringMap = {
added all imports

2025-01-13 16:16 UTC, pokornyd commented on docs/index.md
> +console.log(htmlOutput); // <p>Hello <strong>World!</strong></p>
LET HIM COOK

2025-01-13 16:20 UTC, pokornyd commented on docs/index.md
> +Example showcasing asynchronous transformation of `<img>` tag to `<figure>`, simultaneously uploading the image to Kontent.ai asset library, using SDK `ManagementClient` provided as context:
I rewrote this part altogether and added a new example to showcase usage with handler as well. let me know what you think

2025-01-13 17:34 UTC, pokornyd commented on src/parser/parser-models.ts
> +  "data-external-id": never;
hmm. let me think about this some more. I guess it could be possible, but these type definitions mimic what gets returned from the API. `undefined` was an oversight, it should be `never` as well. it indicates the property is not present in respective API's response.

basically, only the union type `ObjectElementAttributes` is used in the code and it's used as a type parameter.

2025-01-13 17:38 UTC, pokornyd commented on src/transformers/json-transformer/json-transformer.ts
> +        const transformer = transformers.tag[tagNode.tagName] ?? transformers.tag["*"];
I actually prefer it this way tbh. Default resolution of HTML transforms tags along with all attributes. If you want to omit all attributes, you can specify wildcard as specified in the readme: `<${tagNode.tagName}>${children}</${tagNode.tagName}>`. If I make the wildcard mandatory, we should export the `formatAttributes` function at least, to make the attribute rendering process simple.

2025-01-13 17:41 UTC, pokornyd commented on src/transformers/json-transformer/json-transformer.ts
> +export type NodeToString<TContext = unknown> = (
I thought about it. I know typescript doesn't have a special type for HTML strings, but the function signature defines `string` as return type, hence, NodeToString.

2025-01-13 17:45 UTC, pokornyd commented on src/transformers/json-transformer/json-transformer.ts
> +              await transformer?.(tagNode, children, updatedContext)
think I explained it in a different comment already, but nvm. I disagree with default fallback in `transformNodes` and its async version. it returns generic `TOutput`. keeping original node in fallback would require casting it `as unknown as TOutput` or something like that, which me no likey. with `nodesToHtml`, we know the output should be HTML, so we know what to fall back to if wildcard is not specified. with generic, it doesn't make sense to me

2025-01-13 17:46 UTC, pokornyd commented on src/transformers/portable-text-transformer/portable-text-transformer.ts
>  } from "../../transformers/index.js";
you mean the folder path is needlessly deep?

2025-01-13 17:50 UTC, pokornyd commented on src/transformers/portable-text-transformer/portable-text-transformer.ts
> +      const categoryMap: Record<PortableTextItem["_type"], PortableTextItem[]> = {
yeah, this is ugly as a sin and I'm not sure why I haven't moved the accumulator and the map outside the reducer already. well I have now, let me know if it's fine by you

2025-01-13 17:53 UTC, pokornyd commented on src/utils/common-utils.ts
> +export const isTableCell = (node: DomHtmlNode): boolean => isElement(node) && node.tagName === "td";
# :) :) :) :)

2025-01-13 17:53 UTC, pokornyd commented on src/utils/transformer-utils.ts
> +    const traversedNode = callback(node) ?? { ...node };
I'm not even sure this needs to be copied like this in the first place

2025-01-13 18:16 UTC, pokornyd commented on src/parser/parser-models.ts
> +  "data-external-id": never;
alright, discriminated the types and adjusted the code accordingly

2025-01-13 18:52 UTC, pokornyd commented on src/parser/parser-models.ts
> +  "data-external-id": never;
hehe, cancel that. it did actually break something. it has to do with the way the two properties somewhat overlap between DAPI and MAPI. the explicit discriminator is nice, but I need to discriminate the nodes right after parsing, which can only be done by checking which attributes are present, meh

2025-01-16 15:24 UTC, IvanKiral requested changes

2025-01-16 15:24 UTC, IvanKiral commented on README.md
> +https://github.com/kontent-ai/rich-text-resolver-js/blob/6fe68490a32bb304d141cff741fb7e57001550eb/showcase/showcase.ts#L14-L24
Lines are moved :/ you don't see the definition of type, can u fix plz?

2025-01-16 15:24 UTC, IvanKiral commented on README.md
> +### Parsing rich text HTML to a JSON tree
let's talk about whether it is a JSON tree. I think it is a tree of javascript objects. JSON is this https://www.json.org/json-en.html.  If it is indeed wrong, it was probably so even before, however, now when I was reading it, it hit me :D

2025-01-16 15:24 UTC, IvanKiral commented on README.md
> +  const tree = parseHtml(richTextContent);
this is outdated isn't it? I think, you don't have to use parseHtml in this scenario, you just transform rich-text to portable text

2025-01-16 15:24 UTC, IvanKiral commented on README.md
> +Besides default blocks for common elements, Portable Text supports custom blocks, which can represent other entities. Each custom block should extend `ArbitraryTypedObject` to ensure `_key` and `_typ
yes, thx

2025-01-16 15:24 UTC, IvanKiral commented on README.md
> +> For image resolution, you may use `resolveImage` helper function. You can provide it either with a custom resolution method or use provided default implementations.
the implenentation of our resolveImage is probably good enough :)

2025-01-16 15:24 UTC, IvanKiral commented on docs/index.md
> +Example showcasing asynchronous transformation of `<img>` tag to `<figure>`, simultaneously uploading the image to Kontent.ai asset library, using SDK `ManagementClient` provided as context:
looks good

2025-01-16 15:24 UTC, IvanKiral commented on src/parser/parser-models.ts
> +  "data-external-id": never;
not a deal breaker for me :) resolving comment

2025-01-16 15:24 UTC, IvanKiral commented on src/transformers/json-transformer/json-transformer.ts
> +export type NodeToString<TContext = unknown> = (
decided for nodesToHtml

2025-01-16 15:24 UTC, IvanKiral commented on src/transformers/portable-text-transformer/portable-text-transformer.ts
>  } from "../../transformers/index.js";
I mean you are in /src/transformers/portable-text-transformer so:
- ../  -> goes to /src /transformers/
- ../../ -> goes to /src
- ../../transformers -> goes to /src/transfomers (same as first :D)

Also I am not sure why are you importing from index.js. Not sure whether it is a bad practise or not tho. But i gues it might have a bad impact on circular dependencies.

2025-01-16 15:24 UTC, IvanKiral commented on src/transformers/portable-text-transformer/portable-text-transformer.ts
> +      const categoryMap: Record<PortableTextItem["_type"], PortableTextItem[]> = {
it's better, wouldn't it be even nicer with ts-pattern? :D

2025-01-16 15:24 UTC, IvanKiral commented on src/utils/common-utils.ts
> +export const isTableCell = (node: DomHtmlNode): boolean => isElement(node) && node.tagName === "td";
you still have isElement in isBlockElement, isValidElement and isMarkElement

2025-01-16 15:24 UTC, IvanKiral commented on src/utils/transformer-utils.ts
>  export const createMark = (
did you skip this?

2025-01-16 15:24 UTC, IvanKiral commented on src/utils/transformer-utils.ts
> +export const traversePortableText = <
This function still has a couple of weirdos:
1. callback by itself can easily return Node by itself, so you don't have to do it on line 49 :)
2. If I first change the node and just then traverse it, I might lose some of the nodes in the tree, is this an expected behavior? What if I want to explore all the nodes to keep some statistics about them and just remove it?
3. I believe the function is not pure. it changes the original objects. For me, it would make sense to function not to return anything (void) so the end user can see in type that it doesn't create a new array and just transforms the given one.

2025-01-16 15:24 UTC, IvanKiral commented on src/parser/parser-models.ts
> +  "data-asset-external-is"?: string;
external-is? :D (Information system?)

2025-01-16 15:24 UTC, IvanKiral commented on src/transformers/json-transformer/json-transformer.ts
> +
I would probably rename this file -> html-transformer.ts?

2025-01-16 15:24 UTC, IvanKiral commented on src/transformers/portable-text-transformer/portable-text-transformer.ts
> +  return transformNodes(parsedNodes, transformers, { depth: 0, type: "unknown" }) as PortableTextObject[];
I don't get this type cast? I don't think it should be here, but somehow it breaks.. seems sketchy.

2025-01-16 15:24 UTC, IvanKiral commented on src/utils/resolution/html.ts
> +  };
How should this work?, if I provide custom resolver for table, then this one would be used and for the image the default would remain?

2025-01-16 15:24 UTC, IvanKiral commented on src/utils/resolution/html.ts
> +export const toHTML = (blocks: PortableTextObject[], resolvers?: PortableTextHtmlResolvers) => {
We have nodesToHtml (Html not in all camel case) I think, it would be consistent to keep it consistent

2025-01-16 15:24 UTC, IvanKiral commented on src/utils/resolution/html.ts
> +export const toHTML = (blocks: PortableTextObject[], resolvers?: PortableTextHtmlResolvers) => {
I also think it deserves one test for this scenario, HTML contains both table and image and just one is updated in custom resolvers :)

2025-01-16 15:24 UTC, IvanKiral commented on src/utils/resolution/react.tsx
> +export const PortableText = <B extends TypedObject = PortableTextBlock>({
do we have something in readmes about this wrappers? or maybe we can somehow include them in the diagram?, I was a little bit confused for a little :D

2025-01-16 15:48 UTC, IvanKiral commented on src/utils/transformer-utils.ts
> +export const traversePortableText = <
Jiri would like to create just new array, objects wouldn't mind if they were old - it would be something like half-pure :D the performance would suffer, don't know if it is something critical :/

2025-01-16 17:02 UTC, pokornyd commented on README.md
> +https://github.com/kontent-ai/rich-text-resolver-js/blob/6fe68490a32bb304d141cff741fb7e57001550eb/showcase/showcase.ts#L14-L24
they're actually correct now, but the link points to main branch. it will fix itself when merged :)

2025-01-16 17:05 UTC, pokornyd commented on README.md
> +### Parsing rich text HTML to a JSON tree
yeah you're right. but we actually called this JSON transformer from the beginning as you point out :D I'll think of a different name

2025-01-16 17:05 UTC, pokornyd commented on README.md
> +  const tree = parseHtml(richTextContent);
good catch

2025-01-16 17:07 UTC, pokornyd commented on src/utils/transformer-utils.ts
>  export const createMark = (
I forgot to ask -- what does it relate to exactly?

2025-01-16 17:25 UTC, pokornyd commented on src/transformers/portable-text-transformer/portable-text-transformer.ts
> +  return transformNodes(parsedNodes, transformers, { depth: 0, type: "unknown" }) as PortableTextObject[];
I hear you, but this is kind of rooted in the logic. the thing is, when transforming the DomNode array recursively, the nodes get transformed from the bottom and transformed ones are propagated upwards. this means intermediate arrays returned during the recursion contain standalone items such as PortableTextSpan, Reference, etc., which never exist on their own in the resulting portable text array but rather are nested in parent blocks. 

when everything is transformed correctly, you should only have array of top level portable text blocks, hence the cast. I guess some check could be added here.

2025-01-16 17:50 UTC, pokornyd commented on src/transformers/portable-text-transformer/portable-text-transformer.ts
> +  return transformNodes(parsedNodes, transformers, { depth: 0, type: "unknown" }) as PortableTextObject[];
i think the key problem (pun intended) is with `PortableTextSpan` interface. it's the only interface in the union of all portable text types which doesn't allow unknown properties (it doesn't extend `[key: string]: unknown`). I tried removing`PortableTextObject` type altogether and just use `PortableTextItem`, which resulted in this specific issue.

I'd say the cast isn't as problematic tbh. since almost all types allow arbitrary properties, `PortableTextObject` and `PortableTextItem` have a huge overlap. the cast just narrows down the resulting array to top level object types only.

2025-01-16 17:53 UTC, pokornyd commented on src/utils/resolution/html.ts
> +  };
Yep, that's the general idea. the order of the objects being spread should ensure the custom resolver takes precedence over the default one, but keep default resolver for tags not explicitly specified. I'll add a test for this, if there's not one yet

2025-01-16 17:55 UTC, pokornyd commented on src/utils/resolution/react.tsx
> +export const PortableText = <B extends TypedObject = PortableTextBlock>({
there's a highlighted tip explaining this in the readme (line 42). do you think it's sufficient or should this be highlighted even more?

2025-01-16 17:56 UTC, pokornyd commented on src/utils/resolution/html.ts
> +export const toHTML = (blocks: PortableTextObject[], resolvers?: PortableTextHtmlResolvers) => {
let's use the uppercased variant then, as `toHTML` originally comes from external package.

2025-01-17 06:53 UTC, IvanKiral commented on README.md
> +https://github.com/kontent-ai/rich-text-resolver-js/blob/6fe68490a32bb304d141cff741fb7e57001550eb/showcase/showcase.ts#L14-L24
okay sorry then :)

2025-01-17 06:59 UTC, IvanKiral commented on src/transformers/portable-text-transformer/portable-text-transformer.ts
> +  return transformNodes(parsedNodes, transformers, { depth: 0, type: "unknown" }) as PortableTextObject[];
okay I guess, i thought about that, and probably don't have better solution after your explanation

2025-01-17 06:59 UTC, IvanKiral commented on src/utils/resolution/html.ts
> +export const toHTML = (blocks: PortableTextObject[], resolvers?: PortableTextHtmlResolvers) => {
fine by me

2025-01-17 07:01 UTC, IvanKiral commented on src/utils/resolution/react.tsx
> +export const PortableText = <B extends TypedObject = PortableTextBlock>({
it is enough, though i liked you diagram in dms

2025-01-17 09:15 UTC, pokornyd commented on src/transformers/json-transformer/json-transformer.ts
> +
done

2025-01-17 09:19 UTC, pokornyd commented on src/parser/parser-models.ts
> +  "data-asset-external-is"?: string;
ouch

2025-01-17 09:45 UTC, pokornyd commented on src/utils/transformer-utils.ts
>  export const createMark = (
`CreateMark` was an unused method from previous versions, so I just got rid of it altogether.

2025-01-17 10:51 UTC, pokornyd commented on src/utils/transformer-utils.ts
>  export const createMark = (
I used this to retype the property of PortableTextMark though

2025-01-17 10:51 UTC, pokornyd commented on src/utils/transformer-utils.ts
>  export const createMark = (
and removed the eslint rule I added to get around this.

2025-01-17 10:52 UTC, pokornyd commented on src/utils/common-utils.ts
> +export const isTableCell = (node: DomHtmlNode): boolean => isElement(node) && node.tagName === "td";
forgive me master :(

2025-01-17 11:22 UTC, pokornyd commented on src/utils/transformer-utils.ts
> +export const traversePortableText = <
it's now pure-ish and returns a new array, rather than mutating the original one.

2025-01-17 11:34 UTC, pokornyd commented on src/utils/resolution/html.ts
> +export const toHTML = (blocks: PortableTextObject[], resolvers?: PortableTextHtmlResolvers) => {
added the table & image combo test

2025-01-17 12:29 UTC, Enngage commented on showcase/showcase.ts
> -      _ref: "linkedItemOrComponentCodename",
@pokornyd , Would it be possible to change the `_ref` and  `_key` in various objects with the expected value? I.e. in this case you assign a  `codename`, but when using this I have no way of knowing if it's a codename/id or something else entirely. 

If these properties are necessary for some reason and can't be renamed, I think it would be worth adding new custom properties that will represent the ID/codename appropriately.

2025-01-17 12:31 UTC, Enngage commented on tests/transfomers/portable-text-transformer/resolution/vue.resolver.spec.ts
>      table: ({ value }: PortableTextComponentProps<PortableTextTable>) => resolveTable(value, h, toPlainText),
@pokornyd not sure if this was changed, but when testing it I noticed that all properties under `types` were required - meaning you had to provide some sort of implementation even if you only needed to provide a resolver for image. Can these props be made optional instead?

2025-01-20 09:35 UTC, pokornyd commented on showcase/showcase.ts
> -      _ref: "linkedItemOrComponentCodename",
hey @Enngage. this had already been done. the underlying `Reference` type now also contains a `referenceType` string literal, with value of `codename`, `external-id` or `id`, informing you of the nature of the value stored in `_ref`.

the showcase is updated to reflect that, but the readme embed points to main branch version of it. should get sorted after the merge :)

2025-01-20 10:03 UTC, pokornyd commented on tests/transfomers/portable-text-transformer/resolution/vue.resolver.spec.ts
>      table: ({ value }: PortableTextComponentProps<PortableTextTable>) => resolveTable(value, h, toPlainText),
the helper types (`PortableTextHtmlResolvers`, `PortableTextReactResolvers`) are both set to be partial. I didn't create helper type for Vue, but `PortableTextComponents["types"]` appears to be partial by default

2025-01-20 15:39 UTC, IvanKiral requested changes

2025-01-20 15:39 UTC, IvanKiral commented on src/utils/transformer-utils.ts
> +export const traversePortableText = <
nitpick: formatting of generic can be onelined

2025-01-20 15:39 UTC, IvanKiral commented on src/transformers/html-transformer/html-transformer.ts
> +export type NodeToHtml<TContext = unknown> = (
is this unknown necessary?

2025-01-20 15:39 UTC, IvanKiral commented on src/transformers/html-transformer/html-transformer.ts
> +  node: DomHtmlNode<any>,
can't this be `node: DomHtmlNode<unknown>`?

2025-01-20 15:39 UTC, IvanKiral commented on src/transformers/html-transformer/html-transformer.ts
> +export type NodeToHtml<TContext = unknown> = (
check all occurences

2025-01-20 18:40 UTC, pokornyd commented on src/transformers/html-transformer/html-transformer.ts
> +export type NodeToHtml<TContext = unknown> = (
switched to `unknown` in the transformer models. I kept `any` in the internal `PortableTextTransformers` type definition as it would probably need more thorough refactoring. can rewrite it if you insist though

2025-01-20 18:40 UTC, pokornyd commented on src/transformers/html-transformer/html-transformer.ts
> +  node: DomHtmlNode<any>,
yep. changed

2025-01-21 07:51 UTC, IvanKiral commented on src/transformers/html-transformer/html-transformer.ts
> +export type NodeToHtml<TContext = unknown> = (
no its fine

2025-01-21 09:13 UTC, merged